package com.goremember.client.core.styles.colors.material

import androidx.compose.ui.graphics.Color

internal val md_theme_light_primary = Color(0xFF4FD8EB) // Світлий бірюзовий
internal val md_theme_light_onPrimary = Color(0xFFFFFFFF) // Білий
internal val md_theme_light_primaryContainer = Color(0xFF006874) // Темно-бірюзовий
internal val md_theme_light_onPrimaryContainer = Color(0xFF97F0FF) // Світлий бірюзовий
internal val md_theme_light_secondary = Color(0xFFA8D8D8) // М'ятний
internal val md_theme_light_onSecondary = Color(0xFF212121) // Темно-сірий
internal val md_theme_light_secondaryContainer = Color(0xFF004F58) // Темно-бірюзовий
internal val md_theme_light_onSecondaryContainer = Color(0xFF334B4F) // Темно-зелений
internal val md_theme_light_tertiary = Color(0xFFFF9800) // Помаранчевий
internal val md_theme_light_onTertiary = Color(0xFFFFFFFF) // Білий
internal val md_theme_light_tertiaryContainer = Color(0xFFFB8C00) // Трохи темніший помаранчевий
internal val md_theme_light_onTertiaryContainer = Color(0xFF0E1B37) // Темно-синій
internal val md_theme_light_error = Color(0xFFD32F2F) // Червоний
internal val md_theme_light_errorContainer = Color(0xFFFFDAD6) // Світло-рожевий
internal val md_theme_light_onError = Color(0xFFFFFFFF) // Білий
internal val md_theme_light_onErrorContainer = Color(0xFF410002) // Темно-червоний
internal val md_theme_light_background = Color(0xFFFFFFFF) // Білий
internal val md_theme_light_onBackground = Color(0xFF212121) // Темно-сірий
internal val md_theme_light_surface = Color(0xFFF5F5F5) // Світло-сірий
internal val md_theme_light_onSurface = Color(0xFF191C1D) // Темно-сірий
internal val md_theme_light_surfaceVariant = Color(0xFFDBE4E6) // Світло-сірий
internal val md_theme_light_onSurfaceVariant = Color(0xFF3F484A) // Темно-сірий
internal val md_theme_light_outline = Color(0xFFBDBDBD) // Сірий
internal val md_theme_light_inverseOnSurface = Color(0xFFEFF1F1) // Дуже світлий сірий
internal val md_theme_light_inverseSurface = Color(0xFF2E3132) // Темно-сірий
internal val md_theme_light_inversePrimary = Color(0xFF006874) // Темно-бірюзовий
internal val md_theme_light_surfaceTint = Color(0xFF4FD8EB) // Світлий бірюзовий
internal val md_theme_light_outlineVariant = Color(0xFFBFC8CA) // Легкий сірий
internal val md_theme_light_scrim = Color(0xFF000000) // Чорний

internal val md_theme_dark_primary = Color(0xFF006874) // Темно-бірюзовий
internal val md_theme_dark_onPrimary = Color(0xFF97F0FF) // Світлий бірюзовий
internal val md_theme_dark_primaryContainer = Color(0xFF004F58) // Темно-бірюзовий
internal val md_theme_dark_onPrimaryContainer = Color(0xFF4FD8EB) // Світлий бірюзовий
internal val md_theme_dark_secondary = Color(0xFFB1CBD0) // Світло-бірюзовий
internal val md_theme_dark_onSecondary = Color(0xFF1C3438) // Темно-зелений
internal val md_theme_dark_secondaryContainer = Color(0xFF334B4F) // Темно-бірюзовий
internal val md_theme_dark_onSecondaryContainer = Color(0xFFCDE7EC) // Світло-бірюзовий
internal val md_theme_dark_tertiary = Color(0xFFBAC6EA) // Світло-синій
internal val md_theme_dark_onTertiary = Color(0xFF24304D) // Темно-синій
internal val md_theme_dark_tertiaryContainer = Color(0xFF3B4664) // Темно-синій
internal val md_theme_dark_onTertiaryContainer = Color(0xFFDAE2FF) // Світло-блакитний
internal val md_theme_dark_error = Color(0xFFFFB4AB) // Світло-червоний
internal val md_theme_dark_errorContainer = Color(0xFF93000A) // Темно-червоний
internal val md_theme_dark_onError = Color(0xFF690005) // Темно-червоний
internal val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6) // Світло-рожевий
internal val md_theme_dark_background = Color(0xFF191C1D) // Темно-сірий
internal val md_theme_dark_onBackground = Color(0xFFE1E3E3) // Світло-сірий
internal val md_theme_dark_surface = Color(0xFF191C1D) // Темно-сірий
internal val md_theme_dark_onSurface = Color(0xFFE1E3E3) // Світло-сірий
internal val md_theme_dark_surfaceVariant = Color(0xFF3F484A) // Темно-сірий
internal val md_theme_dark_onSurfaceVariant = Color(0xFFBFC8CA) // Легкий сірий
internal val md_theme_dark_outline = Color(0xFF899294) // Світло-сірий
internal val md_theme_dark_inverseOnSurface = Color(0xFF191C1D) // Темно-сірий
internal val md_theme_dark_inverseSurface = Color(0xFFE1E3E3) // Світло-сірий
internal val md_theme_dark_inversePrimary = Color(0xFF4FD8EB) // Світлий бірюзовий
internal val md_theme_dark_surfaceTint = Color(0xFF006874) // Темно-бірюзовий
internal val md_theme_dark_outlineVariant = Color(0xFF3F484A) // Темно-сірий
internal val md_theme_dark_scrim = Color(0xFF000000) // Чорний
